In [ ]:
import tensorflow as tf

# COMMON TERMS
#### SCALAR: A single number
#### VECTOR: A number with direction(E.G windspeed with direction)
#### MATRIX: Matrix is 2D array of numbers
#### TENSOR: A n-dimensional array of numbers (where n can be any number,
##### 0 D TENSOR-->Scalar
##### 1 D TENSOR-->Vector)

In [ ]:
array=tf.constant([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])
print(array)
print(array.ndim)
print(array.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]], shape=(3, 2, 2), dtype=int32)
3
(3, 2, 2)


# DIFFERENCE BETWEEN VARIABLE AND CONSTA    NT

In [ ]:
var=tf.Variable([10,7])
const=tf.constant([10,7])
var[0].assign(7)
print(var)
print(const)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


you can assign only to variable not to constant

# CREATING RANDOM TENSORS 

### USING UNIFORM

In [ ]:
random1=tf.random.Generator.from_seed(42)  #setting seed for reproduceability
random1=random1.uniform(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
### USING NORMAL

In [ ]:
random2=tf.random.Generator.from_seed(42)  #setting seed for reproduceability
random2=random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

# SHUFFLING ORDER OF ELEMENTS IN TENSOR

We shuffle the elements, so that we can initiate the random weights to input data to help our model learn from NEURAL NETWORK

In [ ]:
notShuffled=tf.constant([[1,2],[3,4],[5,6]])
print('Not Shuffled :\n',notShuffled)

Not Shuffled :
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


### USING GLOBAL SEEDING METHOD
once the seed is setted globally,it will result in same output for every run

In [ ]:
tf.random.set_seed(42)
Shuffled=tf.random.shuffle(notShuffled)
print('Shuffled:\n',Shuffled)

Shuffled:
 tf.Tensor(
[[3 4]
 [5 6]
 [1 2]], shape=(3, 2), dtype=int32)


### OPERATIONAL SEEDING METHOD
Here the seeding is not done globally,so every time you run, you get different shuffling

In [ ]:
Shuffled=tf.random.shuffle(notShuffled,seed=42)
print('Shuffled:\n',Shuffled)

Shuffled:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


### ONES AND ZEROS IN TENSORFLOW

In [ ]:
tf_1=tf.ones(shape=(3,4))
tf_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf_0=tf.zeros(shape=(3,4))
tf_0

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### TURNING NUMPY ARRAY INTO TENSORS

In [ ]:
import numpy as np
np_array=np.arange(1,25)
print('Data type of np_array:',np_array.dtype)
np_array

Data type of np_array: int64


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np_array1=np.arange(1,25,dtype=np.int32)
np_array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# 2 sub array , where each array has 3 rows and 4 columns
np_arrayTensor=tf.constant(np_array1,shape=(2,3,4))
np_arrayTensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

**Difference between numpy and tensor is that, tensor can run on GPU(much faster numerical computing)**

**GETTING INFO FROM TENSORS**

SHAPE: length(no.of elements) of each dimension of tensor.

RANK: no.of tensor dimension--> SCALAR=0,VECTOR=1,MATRIX=2,TENSOR=n.

AXIS/DIMENSION: a particular dimension of tensor.

SIZE: total no.of items in tensor

In [ ]:
#RANK 4 TENSOR
rank4Tensor=tf.zeros(shape=(2,3,4,5))  #2 divisions 3 sub divisions inside each, with 4 rows and 5 columns in each sub divisions of divisions.
rank4Tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4Tensor[0]  #1 st division from total 2 divisions 

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
#GETTING VARIOUS ATTRIBUTES OF TENSORS
print('Data type of each element:',rank4Tensor.dtype)
print('Rank(no.of dimensions):',rank4Tensor.ndim)
print('Shape of tensor:',rank4Tensor.shape)
print('Element along the 0 axis:',rank4Tensor[0])
print('Element along the last axis:',rank4Tensor[-1])
print('Total no.of element in tensor:',np.size(rank4Tensor))

Data type of each element: <dtype: 'float32'>
Rank(no.of dimensions): 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Element along the last axis: tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total no.of element in tensor: 120


## INDEXING AND EXPANDING THE TENSORS

In [ ]:
#Indexing in tensorflow is same as python
#normal list
L=[1,2,3,4,5]
L[:2]

[1, 2]

In [ ]:
#In tensors
rank4Tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Getting first element from each dimension from each index except the final one
rank4Tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# CREATING RANK 2 TENSOR
rank2Tensor=tf.constant([[10,7],[3,4]])
rank2Tensor.shape,rank2Tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
L,L[-1]

([1, 2, 3, 4, 5], 5)

In [ ]:
rank2Tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [ ]:
# ADDING 1 EXTRA DIMENSION TO rank2Tensor
rank3Tensor=rank2Tensor[...,tf.newaxis]  #on;y keep 3 dots(...)
rank3Tensor.shape,rank3Tensor.ndim

(TensorShape([2, 2, 1]), 3)

In [ ]:
#ALTERNATE TO NEWAXIS
B=tf.expand_dims(rank2Tensor,axis=-1) # -1 means adding 3rd axis at last
B.shape,B.ndim

(TensorShape([2, 2, 1]), 3)

In [ ]:
B=tf.expand_dims(rank2Tensor,axis=0)  #at first adding the new axis
B.shape,B.ndim

(TensorShape([1, 2, 2]), 3)

In [ ]:
B=tf.expand_dims(rank2Tensor,axis=1)   #adding new axis in middle
B.shape,B.ndim

(TensorShape([2, 1, 2]), 3)

## MANIPULATING TENSORS USING BASIC OPERATIONS

In [ ]:
    tensor=tf.constant([[10,7],[3,4]])
    tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#METHOD 1
print('ADDITION:',tensor+10)
print('SUBTRACTION:',tensor-10)
print('MULTIPLICATION:',tensor*10)

ADDITION: tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
SUBTRACTION: tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
MULTIPLICATION: tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


In [ ]:
#METHOD 2
print('ADDITION:',tf.add(tensor,10))
print('SUBTRACTION:',tf.subtract(tensor,10))
print('MULTIPLICATION:',tf.multiply(tensor,10))


ADDITION: tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
SUBTRACTION: tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
MULTIPLICATION: tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


**VERY IMPORTANT MATHEMATICAL OPERATION IN NEURAL NETWORK**

In [ ]:
#multiplying 2 matrices
#METHOD 1
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#METHOD 2
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#MATRIX MULTIPLICATION
x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.constant([[1,2],[3,4],[5,6]])
x.shape,y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
tf.matmul(x,y)

InvalidArgumentError: ignored

In [ ]:
Y=tf.reshape(y,shape=(2,3))
x.shape,Y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(x,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [ ]:
#TRANSPOSE OF MATRIX
x,tf.transpose(x),Y,tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [ ]:
#MATRIX MULTIPLICATION OF TWO TRANSPOSES
tf.matmul(tf.transpose(x),tf.transpose(Y))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 49],
       [28, 64]], dtype=int32)>

### DOT PRODUCT

matrix multiplication is also referred to as DOT PRODUCT .You can perform using
**tf.matmul() or tf.tensordot()**

In [ ]:
#DOT PRODUCT FOR x and Y matrices
tf.tensordot(tf.transpose(x),tf.transpose(Y),axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 49],
       [28, 64]], dtype=int32)>

### CHANGING DATA TYPE

In [ ]:
c=tf.constant([2,3])
c.dtype

tf.int32

In [ ]:
#changing to float32 in different ways
d=tf.constant([2,3],tf.float32)
print(d)
d1=tf.cast(c,dtype=tf.float32)
print(d1)
d2=tf.cast(c,tf.float32)
print(d2)

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [ ]:
#GETTING ABSOLUTE VALUES
neg=tf.constant([-10,-5])
print('Negative numbers:',neg)
print('Absolute numbers from negative:',tf.abs(neg))

Negative numbers: tf.Tensor([-10  -5], shape=(2,), dtype=int32)
Absolute numbers from negative: tf.Tensor([10  5], shape=(2,), dtype=int32)


In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))
E.ndim,E.shape,tf.size(E)

(1, TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [ ]:
print('Minimum value:',tf.reduce_min(E))
print('Maximum value:',tf.reduce_max(E))
print('Average value:',tf.reduce_mean(E))
print('Sum value:',tf.reduce_sum(E))
# print('SD value:',tf.math.reduce_std(E))
# print('Variance value:',tf.math.reduce_variance(E))

Minimum value: tf.Tensor(7, shape=(), dtype=int64)
Maximum value: tf.Tensor(97, shape=(), dtype=int64)
Average value: tf.Tensor(51, shape=(), dtype=int64)
Sum value: tf.Tensor(2567, shape=(), dtype=int64)


### FINDING POSITIONAL MAXIMUM AND MINIMUM

In [ ]:
#CREATE A TENSOR WITH 50 VALUES BETWEEN 0 & 1
F=tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.06498527, 0.25521208, 0.14708808, 0.80979656, 0.13897805,
       0.16683736, 0.08441661, 0.97291418, 0.26835297, 0.51940024,
       0.08633375, 0.4989261 , 0.00545392, 0.77343898, 0.71228828,
       0.97431793, 0.84392882, 0.61363656, 0.09065775, 0.95826542,
       0.73750987, 0.35638098, 0.43067757, 0.2255137 , 0.08410223,
       0.61512261, 0.78441863, 0.88938561, 0.9989307 , 0.45398431,
       0.63891419, 0.41019199, 0.31234717, 0.35196437, 0.59030194,
       0.76043195, 0.84739709, 0.6401708 , 0.66225485, 0.51019179,
       0.40894387, 0.15341491, 0.05642931, 0.52894137, 0.0223441 ,
       0.34022777, 0.43804095, 0.03732921, 0.13658972, 0.79505397])>

In [ ]:
#FINDING THE MAX ELEMENT POSITION OF F
print(tf.argmax(F))      #the position
print(tf.reduce_max(F))  #the value
#FINDING THE MIN ELEMENT POSITION OF F
print(tf.argmin(F))      #the position
print(tf.reduce_min(F))  #the value

tf.Tensor(28, shape=(), dtype=int64)
tf.Tensor(0.9989307044510953, shape=(), dtype=float64)
tf.Tensor(12, shape=(), dtype=int64)
tf.Tensor(0.005453918995694584, shape=(), dtype=float64)


In [ ]:
print(f"The max value of F:{tf.reduce_max(F).numpy()}")
print('The max value of F:',F[tf.argmax(F)].numpy())
print(f"The max value of F is at position:{tf.argmax(F).numpy()}")

The max value of F:0.9989307044510953
The max value of F: 0.9989307044510953
The max value of F is at position:28


### ONE HOT ENCODING

In [ ]:
print(L)
#ONE HOT ENCODE
tf.one_hot(L,depth=3)  #depth gives no.of columns,len(L) gives no.of rows

[1, 2, 3, 4, 5]


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
#SPECIFY CUSTOM VALUES FOR ON AND OFF ENCODING
tf.one_hot(L,depth=4,on_value='We are live!',off_value='offline')

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'offline', b'We are live!', b'offline', b'offline'],
       [b'offline', b'offline', b'We are live!', b'offline'],
       [b'offline', b'offline', b'offline', b'We are live!'],
       [b'offline', b'offline', b'offline', b'offline'],
       [b'offline', b'offline', b'offline', b'offline']], dtype=object)>

### SQUARE,LOG,SQRT

In [ ]:
#CREATE A TENSOR
H=tf.constant(np.arange(1,10))
print(H)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)


In [ ]:
#SQUARE
print('SQUARE OF H:\n',tf.square(H).numpy())  # you can also use tf.square(H)
#SQRT
H=tf.cast(H,tf.float32)
print('SQRT OF H:\n',tf.sqrt(H).numpy())
#LOG
print('LOG OF H:\n',tf.math.log(H).numpy())

SQUARE OF H:
 [ 1  4  9 16 25 36 49 64 81]
SQRT OF H:
 [1.        1.4142137 1.7320509 2.        2.2360682 2.4494898 2.6457515
 2.8284273 3.0000002]
LOG OF H:
 [0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246]


### MANIPULATING tf.Variable TENSOR

In [ ]:
#CREATE A  VARIABLE TENSOR
I=tf.Variable(np.arange(0,5))  # you can also use np.arange(5)
print(I)

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>


In [ ]:
#ASSIGN THE FINAL VALUE - NEW VALUE OF 50
#METHOD 1
I.assign([0,1,2,3,50])
print(I.numpy())

[ 0  1  2  3 50]


### TENSOR AND NUMPY ARRAY
By default ,data type of

**numpy-->float64**

**tensor-->float32**

**Tensors can be created from Numpy array**

In [ ]:
#CREATE A TENSOR FROM NUMPY ARRAY
J=tf.constant(np.array([3.,7.,10]))
print(J)
#CONVERTING A TENSOR J TO NUMPY WITH np.array
print(np.array(J),type(np.array(J)))
#CONVERT  A TENSOR J TO NUMPY WITH .numpy()
print(J.numpy(),type(J.numpy()))

tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float64)
[ 3.  7. 10.] <class 'numpy.ndarray'>
[ 3.  7. 10.] <class 'numpy.ndarray'>


In [ ]:
#CREATE A TENSOR FROM NUMPY AND FORM AN ARRAY
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

##@tensor Function

In [ ]:
#CREATE A SAMPLE FUNCTION
def function(x,y):
  return x**2+y;

x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

###FINDING ACCESS TO GPUs

In [ ]:
print('Number of GPU available:',len(tf.config.experimental.list_physical_devices('GPU')))

Number of GPU available: 1


In [ ]:
!nvidia-smi

Thu May  5 09:52:33 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0    56W / 149W |    147MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you have access to a GPU, Tensorflow will automatically use it whenever possible