## BUILDING BLOCKS OF DEEP LEARNING AND TENSORFLOW

In [ ]:
#importing libraries
import tensorflow as tf
import numpy as np

### TASK 1

In [ ]:
#creating tilde(~) separated customer record
custId='100';custName='John';email='john12@gmail.com';phone='9843275982';city='Mumbai';gender='Male';date_of_birth='09-03-1999'
List=[custId,custName,email,phone,city,gender,date_of_birth]
a=tf.strings.join(List,separator= "~")
print(a)

tf.Tensor(b'100~John~john12@gmail.com~9843275982~Mumbai~Male~09-03-1999', shape=(), dtype=string)


In [ ]:
#extracting random number of characters from the strings
for i in List:
  print('The string is',i,end='  ')
  print(tf.strings.substr(i,int(np.random.randint(1,len(i),1)),int(np.random.randint(1,len(i),1))))

The string is 100  tf.Tensor(b'0', shape=(), dtype=string)
The string is John  tf.Tensor(b'hn', shape=(), dtype=string)
The string is john12@gmail.com  tf.Tensor(b'ma', shape=(), dtype=string)
The string is 9843275982  tf.Tensor(b'3275982', shape=(), dtype=string)
The string is Mumbai  tf.Tensor(b'bai', shape=(), dtype=string)
The string is Male  tf.Tensor(b'al', shape=(), dtype=string)
The string is 09-03-1999  tf.Tensor(b'-1999', shape=(), dtype=string)


### TASK 2

In [ ]:
#creating 3x3 character constant matrix
matrix=tf.constant([['indigo','violet','programmer'],['computer','training','kitchen'],['array','instagram','bluetooth']])
print(matrix)
print('Shape of matrix=',matrix.shape)
print('Dimension of matrix=',matrix.ndim)

tf.Tensor(
[[b'indigo' b'violet' b'programmer']
 [b'computer' b'training' b'kitchen']
 [b'array' b'instagram' b'bluetooth']], shape=(3, 3), dtype=string)
Shape of matrix= (3, 3)
Dimension of matrix= 2


### TASK 3

In [ ]:
#Create a constant and assign a value
product_price=tf.constant(1895.2)
print(product_price)
#convert its datatype to float16
product_price=tf.constant(1895.2,tf.float16)
print(product_price)

tf.Tensor(1895.2, shape=(), dtype=float32)
tf.Tensor(1895.0, shape=(), dtype=float16)


### TASK 4

In [ ]:
#create 5x3 array with int16
marks=tf.constant([[10,20,30],[40,50,60],[70,80,90],[25,35,45],[55,65,75]],tf.int16)
print('Old marks:\n',marks)
#update the value with random numbers
marks=tf.constant(np.random.randint(10,100,15).reshape(5,3))
print('Updated marks:\n',marks)

Old marks:
 tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 45]
 [55 65 75]], shape=(5, 3), dtype=int16)
Updated marks:
 tf.Tensor(
[[31 49 92]
 [72 29 49]
 [92 70 35]
 [99 74 19]
 [15 21 54]], shape=(5, 3), dtype=int64)


### TASK 5

In [ ]:
#creating test data
test_data=np.random.randint(1,100,150)
print('The test data is:\n',test_data)
#creating 2 constants-coefficients
a=tf.constant(2)
b=tf.constant(1)
#y as placeholder
y=a+(b*test_data)
#predicting
print('The predictions are:\n',y)

The test data is:
 [34 71 55 91 69 74 16 70 73 40 40 55 21 68 50 35 54 58 75 43 73 79 31 88
  6 17 20 95 76 55 83 73 40 79 25  4 71 90 58 34  9 57 25 74 68 77 35 78
 23  9 84 29 57 94 31 88 11 77 49 67 33 86 97 69 10 57 59 71 51 39 32 29
 70 32 55 39 30 13 50 10 93 98 58 63 19 98 65 58 26  4 71 53 51 94 38 14
 91 81 85 92 90 63 80 30 25 51 10 64 20 47 65 33 92 95 51 51  2 42  8 30
 50  5 29 92 30 46 11 95  2 92 87 92 31 39 15 51 92 53 11 35 22 96 81 32
 53 21 19  5 44 58]
The predictions are:
 tf.Tensor(
[ 36  73  57  93  71  76  18  72  75  42  42  57  23  70  52  37  56  60
  77  45  75  81  33  90   8  19  22  97  78  57  85  75  42  81  27   6
  73  92  60  36  11  59  27  76  70  79  37  80  25  11  86  31  59  96
  33  90  13  79  51  69  35  88  99  71  12  59  61  73  53  41  34  31
  72  34  57  41  32  15  52  12  95 100  60  65  21 100  67  60  28   6
  73  55  53  96  40  16  93  83  87  94  92  65  82  32  27  53  12  66
  22  49  67  35  94  97  53  53   4  44  10  32  52

### TASK 6

In [ ]:
#create dictionary with 3 pairs
currency = {'India':'Rupee', 'America':'Dollar','Europe':'Euros'}
print('Dictionary :',currency)
print('Size of dictionary:',len(currency))
#converting to tensors and printing the keys 
t_currency_keys = tf.convert_to_tensor(list(currency.keys()))
print(t_currency_keys)
#converting to tensors and printing the values
t_currency_values = tf.convert_to_tensor(list(currency.values()))
print(t_currency_values)

Dictionary : {'India': 'Rupee', 'America': 'Dollar', 'Europe': 'Euros'}
Size of dictionary: 3
tf.Tensor([b'India' b'America' b'Europe'], shape=(3,), dtype=string)
tf.Tensor([b'Rupee' b'Dollar' b'Euros'], shape=(3,), dtype=string)


### TASK 7

In [ ]:
#creating 2 arrays with 4 products-no.of units,unit price
unit=[5,10,15,20]
unit_price=[10,20,30,40]
for i in range(0, len(unit)):
    total=unit[i] * unit_price[i]
#getting the grand total of all 4 products
print('Grand total=',total)                

Grand total= 800


## END