In [2]:
import numpy as np

In [3]:
pwd

'C:\\Users\\Admin'

In [4]:
# TASK 1           
from numpy import genfromtxt
main=genfromtxt("b.csv",delimiter=',',skip_header=1)
print(main)
X1=main.T
Y1=np.count_nonzero(X1[1]>320)
print('Total no.of students whose GRE score is greater than 320 is',Y1)


[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]
Total no.of students whose GRE score is greater than 320 is 163


In [6]:
# TASK 2

Z2=np.where(main[:,2]>110)
print('Admission possibility of students whose TOEFL score is more than 110 is')
print(main[Z2,0:9:8])

Admission possibility of students whose TOEFL score is more than 110 is
[[[  1.     0.92]
  [  6.     0.9 ]
  [ 12.     0.84]
  [ 13.     0.78]
  [ 22.     0.7 ]
  [ 23.     0.94]
  [ 24.     0.95]
  [ 25.     0.97]
  [ 26.     0.94]
  [ 33.     0.91]
  [ 34.     0.9 ]
  [ 35.     0.94]
  [ 44.     0.87]
  [ 45.     0.91]
  [ 47.     0.86]
  [ 48.     0.89]
  [ 50.     0.78]
  [ 53.     0.78]
  [ 54.     0.72]
  [ 65.     0.52]
  [ 66.     0.55]
  [ 67.     0.61]
  [ 70.     0.78]
  [ 71.     0.94]
  [ 72.     0.96]
  [ 73.     0.93]
  [ 76.     0.72]
  [ 77.     0.74]
  [ 82.     0.96]
  [ 84.     0.92]
  [ 85.     0.94]
  [ 98.     0.86]
  [ 99.     0.9 ]
  [100.     0.79]
  [105.     0.74]
  [107.     0.87]
  [108.     0.91]
  [109.     0.93]
  [121.     0.94]
  [122.     0.94]
  [127.     0.85]
  [128.     0.78]
  [129.     0.84]
  [130.     0.92]
  [131.     0.96]
  [134.     0.79]
  [135.     0.89]
  [139.     0.8 ]
  [142.     0.9 ]
  [143.     0.92]
  [144.     0.97]
  [145.   

In [7]:
# TASK 3
x3= np.array(sorted(main, key = lambda x: x[1], reverse = True))
print("Top 11 GRE toppers:")
print(x3[0:11,[0,1]])
y3= np.array(sorted(main, key = lambda x: x[2], reverse = True))
print("Top 8 TOEFL toppers:")
print(y3[0:9,[0,2]])

Top 11 GRE toppers:
[[ 26. 340.]
 [ 34. 340.]
 [ 82. 340.]
 [ 85. 340.]
 [144. 340.]
 [203. 340.]
 [285. 340.]
 [385. 340.]
 [ 48. 339.]
 [131. 339.]
 [149. 339.]]
Top 8 TOEFL toppers:
[[ 26. 120.]
 [ 82. 120.]
 [ 98. 120.]
 [144. 120.]
 [203. 120.]
 [204. 120.]
 [213. 120.]
 [298. 120.]
 [ 24. 119.]]


In [9]:
# TASK 4
x4=np.where((main[:,1]>=300) & (main[:,1]<=305) &(main[:,4]==3.5) & (main[:,7]==1))
print('According to the given condition displaying Serial no and TOEFL scores:')
print(main[:,[0,2]][x4])
                               

According to the given condition displaying Serial no and TOEFL scores:
[[113. 107.]
 [210. 104.]
 [358. 104.]]


In [13]:
# TASK 5    
amount=np.random.randint(5000,10001,size=(400,1))
amount

array([[7862],
       [5962],
       [9718],
       [7505],
       [8452],
       [5474],
       [5660],
       [5047],
       [6574],
       [9420],
       [7945],
       [6581],
       [8372],
       [6797],
       [5318],
       [8934],
       [5714],
       [7705],
       [9890],
       [9706],
       [7745],
       [9966],
       [6712],
       [5619],
       [8762],
       [5467],
       [9844],
       [8671],
       [6305],
       [8995],
       [7275],
       [5822],
       [8051],
       [7932],
       [6990],
       [5082],
       [7580],
       [5561],
       [8199],
       [9210],
       [6714],
       [7757],
       [7401],
       [9553],
       [8814],
       [9117],
       [8521],
       [9807],
       [8934],
       [5520],
       [9976],
       [8623],
       [5330],
       [9938],
       [9325],
       [8581],
       [8833],
       [8342],
       [6305],
       [9446],
       [9383],
       [9623],
       [5529],
       [8798],
       [8165],
       [5076],
       [52

In [14]:
main=np.concatenate((main,amount),axis=1)
main

array([[1.000e+00, 3.370e+02, 1.180e+02, ..., 1.000e+00, 9.200e-01,
        7.862e+03],
       [2.000e+00, 3.240e+02, 1.070e+02, ..., 1.000e+00, 7.600e-01,
        5.962e+03],
       [3.000e+00, 3.160e+02, 1.040e+02, ..., 1.000e+00, 7.200e-01,
        9.718e+03],
       ...,
       [3.980e+02, 3.300e+02, 1.160e+02, ..., 1.000e+00, 9.100e-01,
        6.239e+03],
       [3.990e+02, 3.120e+02, 1.030e+02, ..., 0.000e+00, 6.700e-01,
        5.818e+03],
       [4.000e+02, 3.330e+02, 1.170e+02, ..., 1.000e+00, 9.500e-01,
        7.650e+03]])

In [15]:
main.shape

(400, 10)

In [16]:
#scholarship >9000
X=np.where(main[:,9]>9000)
main[X]

array([[3.000e+00, 3.160e+02, 1.040e+02, 3.000e+00, 3.000e+00, 3.500e+00,
        8.000e+00, 1.000e+00, 7.200e-01, 9.718e+03],
       [1.000e+01, 3.230e+02, 1.080e+02, 3.000e+00, 3.500e+00, 3.000e+00,
        8.600e+00, 0.000e+00, 4.500e-01, 9.420e+03],
       [1.900e+01, 3.180e+02, 1.100e+02, 3.000e+00, 4.000e+00, 3.000e+00,
        8.800e+00, 0.000e+00, 6.300e-01, 9.890e+03],
       [2.000e+01, 3.030e+02, 1.020e+02, 3.000e+00, 3.500e+00, 3.000e+00,
        8.500e+00, 0.000e+00, 6.200e-01, 9.706e+03],
       [2.200e+01, 3.250e+02, 1.140e+02, 4.000e+00, 3.000e+00, 2.000e+00,
        8.400e+00, 0.000e+00, 7.000e-01, 9.966e+03],
       [2.700e+01, 3.220e+02, 1.090e+02, 5.000e+00, 4.500e+00, 3.500e+00,
        8.800e+00, 0.000e+00, 7.600e-01, 9.844e+03],
       [4.000e+01, 3.070e+02, 1.080e+02, 2.000e+00, 4.000e+00, 3.500e+00,
        7.700e+00, 0.000e+00, 4.800e-01, 9.210e+03],
       [4.400e+01, 3.320e+02, 1.170e+02, 4.000e+00, 4.500e+00, 4.000e+00,
        9.100e+00, 0.000e+00, 8.700e-

In [18]:
# TASK 6
a=np.where(main[:,9]>9000)
print('SOP and LOR score for students who are getting scholarship more than 9000 are:')
print(main[:,[0,4,5]][a])

SOP and LOR score for students who are getting scholarship more than 9000 are:
[[  3.    3.    3.5]
 [ 10.    3.5   3. ]
 [ 19.    4.    3. ]
 [ 20.    3.5   3. ]
 [ 22.    3.    2. ]
 [ 27.    4.5   3.5]
 [ 40.    4.    3.5]
 [ 44.    4.5   4. ]
 [ 46.    5.    4. ]
 [ 48.    4.5   4. ]
 [ 51.    2.5   4.5]
 [ 54.    4.    2.5]
 [ 55.    3.    3.5]
 [ 60.    2.    2. ]
 [ 61.    3.    3. ]
 [ 62.    4.    3. ]
 [ 71.    5.    5. ]
 [ 72.    5.    5. ]
 [ 81.    2.    3. ]
 [ 94.    3.    3. ]
 [ 98.    4.    4. ]
 [ 99.    5.    4.5]
 [108.    3.5   4.5]
 [110.    5.    4. ]
 [118.    2.    2.5]
 [126.    2.    3. ]
 [127.    4.    3. ]
 [131.    4.    4.5]
 [155.    3.    3.5]
 [156.    3.    3. ]
 [161.    1.5   2. ]
 [164.    3.5   3. ]
 [183.    3.    3.5]
 [185.    2.5   4. ]
 [187.    3.5   3. ]
 [188.    4.5   3.5]
 [189.    4.5   3.5]
 [190.    5.    5. ]
 [193.    4.5   4. ]
 [198.    3.5   2.5]
 [209.    3.    3. ]
 [210.    3.5   4. ]
 [216.    5.    4.5]
 [227.    3.5   4.

In [25]:
# TASK 7
x7=np.where((main[:,1]>315) & (main[:,2]>115)& (main[:,7]==1))
print('Serial number of students who are eligible for $1000 scholarship are:')
print(main[:,0][x7])
print('count=',np.size(x7))

Serial number of students who are eligible for $1000 scholarship are:
[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]
count= 41


In [26]:
#updating
main[:,9][x7]=1000
main[:,[0,9]][x7]

array([[   1., 1000.],
       [  23., 1000.],
       [  24., 1000.],
       [  25., 1000.],
       [  26., 1000.],
       [  33., 1000.],
       [  53., 1000.],
       [  71., 1000.],
       [  82., 1000.],
       [  98., 1000.],
       [  99., 1000.],
       [ 108., 1000.],
       [ 109., 1000.],
       [ 121., 1000.],
       [ 122., 1000.],
       [ 130., 1000.],
       [ 139., 1000.],
       [ 142., 1000.],
       [ 144., 1000.],
       [ 149., 1000.],
       [ 152., 1000.],
       [ 172., 1000.],
       [ 177., 1000.],
       [ 188., 1000.],
       [ 194., 1000.],
       [ 203., 1000.],
       [ 204., 1000.],
       [ 213., 1000.],
       [ 214., 1000.],
       [ 215., 1000.],
       [ 216., 1000.],
       [ 260., 1000.],
       [ 286., 1000.],
       [ 287., 1000.],
       [ 326., 1000.],
       [ 338., 1000.],
       [ 362., 1000.],
       [ 373., 1000.],
       [ 386., 1000.],
       [ 398., 1000.],
       [ 400., 1000.]])

In [32]:
# TASK 8
cgpa=np.where((main[:,6]>=8.0) & (main[:,6]<=8.5))
print('Total no.of students who have obtained CGPA from 8.0 to 8.5 are',np.size(cgpa))

Total no.of students who have obtained CGPA from 8.0 to 8.5 are 122


In [49]:
# TASK 9
initial=main[0:50]
avg_sop=np.mean(initial[:,4])
avg_lor=np.mean(initial[:,5])
print('Average of SOP score is more than LOR score by',((avg_sop-avg_lor)/avg_sop)*100,'%')


Average of SOP score is more than LOR score by 3.3802816901408357 %


In [56]:
# TASK 10
#spread/distribution of scholarship amount
s1=np.mean(main[:,9])
print('Average value of scholarship amount=',s1)
s2=np.max(main[:,9])
print('Maximum value of scholarship amount=',s2)
s3=np.min(main[:,9])

print('Minimum value of scholarship amount=',s3)
s4=np.median(main[:,9])
print('Median value of scholarship amount=',s4)


Average value of scholarship amount= 6922.2325
Maximum value of scholarship amount= 9976.0
Minimum value of scholarship amount= 1000.0
Median value of scholarship amount= 7442.5


In [80]:
# TASK 11
adm=np.where(main[:,8]>=0.95)
# np.size(adm)
print('GRE,TOEFL,CGPA required by students for atleast 95% admission possibility are:\n',main[:,[0,1,2,6]][adm],'\n')
print('Minimum GRE score required:',np.min(main[:,[1]][adm]),'\n')
print('Average GRE score required:',np.mean(main[:,[1]][adm]),'\n')
print('Minimum TOEFL score required:',np.min(main[:,[2]][adm]),'\n')
print('Average TOEFL score required:',np.mean(main[:,[2]][adm]),'\n')
print('Minimum CGPA required:',np.min(main[:,[6]][adm]),'\n')
print('Average CGPA required:',np.mean(main[:,[6]][adm]))

GRE,TOEFL,CGPA required by students for atleast 95% admission possibility are:
 [[ 24.   334.   119.     9.7 ]
 [ 25.   336.   119.     9.8 ]
 [ 72.   336.   112.     9.76]
 [ 82.   340.   120.     9.5 ]
 [131.   339.   114.     9.76]
 [144.   340.   120.     9.92]
 [149.   339.   116.     9.8 ]
 [203.   340.   120.     9.91]
 [204.   334.   120.     9.87]
 [213.   338.   120.     9.66]
 [214.   333.   119.     9.78]
 [373.   336.   119.     9.62]
 [385.   340.   113.     9.74]
 [386.   335.   117.     9.82]
 [400.   333.   117.     9.66]] 

Minimum GRE score required: 333.0 

Average GRE score required: 336.8666666666667 

Minimum TOEFL score required: 112.0 

Average TOEFL score required: 117.66666666666667 

Minimum CGPA required: 9.5 

Average CGPA required: 9.753333333333334


In [81]:
# END